### ISSUE TITLE
where to define python modules to load

### ISSUE THREAD

**Issue by roolio** [kidanger/vpv-plugins#2]
Hello, I'm wondering where to define pythons scripts to load? 
I've added 
```lua
plugins.load('python','python/python')
```
in the .vprc, to enable python scripts, but say I want to load show-date, seq2gif and date-to-plot. 

I've added 
```python 
    load('show-date')
    load('seq2gif')
    load('date-to-plot')
``` 
in the __main__  of plugins.py, but I'd like to know the orthodox way to do it 

Thanks a lot

**Comment by kidanger** [comment]
Hello,
You can load python plugins from lua using the `load` function:
```lua
plugins.load('python', 'python/python')
plugins.python.load 'show-date'
```

**Comment by roolio** [comment]
Perfect! 
Thanks a lot for your answer (and kudos for the great vpv!)
